# Generated by Django 4.2.11 on 2024-03-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emotional_Analysis', '0003_alter_user_options_remove_user_c_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_num', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('comment_text', models.CharField(max_length=300)),
                ('comment_date', models.CharField(default=None, max_length=50)),
                ('comment_time', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
