# Generated by Django 4.2.11 on 2024-03-24 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Emotional_Analysis', '0006_alter_comment_comment_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
